// @vitest-environment node
import { afterEach, describe, expect, it, vi } from "vitest";

import type { Item } from "../data/inventoryData.ts";

import { downloadPdf } from "./downloadPdf.ts";
import { generateInventoryListPdf } from "./inventoryListPdf.ts";
import { loadInventoryPdfAssets } from "./inventoryPdfAssets.ts";
import { printInventoryList } from "./printInventoryList.ts";

vi.mock("./downloadPdf.ts", () => ({ downloadPdf: vi.fn() }));
vi.mock("./inventoryPdfAssets.ts", () => ({
	loadInventoryPdfAssets: vi.fn(),
}));
vi.mock("./inventoryListPdf.ts", () => ({
	generateInventoryListPdf: vi.fn(),
	inventoryListPdfFilename: () => "inventory-list-test.pdf",
}));

const ROWS: Item[] = [];

afterEach(() => {
	vi.restoreAllMocks();
	vi.mocked(downloadPdf).mockReset();
	vi.mocked(loadInventoryPdfAssets).mockReset();
	vi.mocked(generateInventoryListPdf).mockReset();
});

describe("printInventoryList", () => {
	it("downloads the generated bytes under the dated filename", async () => {
		const bytes = new Uint8Array([1, 2, 3]);
		vi.mocked(loadInventoryPdfAssets).mockResolvedValue(
			{} as Awaited<ReturnType<typeof loadInventoryPdfAssets>>
		);
		vi.mocked(generateInventoryListPdf).mockResolvedValue(bytes);

		await printInventoryList(ROWS);

		expect(downloadPdf).toHaveBeenCalledWith(
			bytes,
			"inventory-list-test.pdf"
		);
	});

	it("logs instead of rejecting when the assets cannot be fetched", async () => {
		const failure = new Error("network down");
		const error = vi
			.spyOn(console, "error")
			.mockImplementation(() => undefined);
		vi.mocked(loadInventoryPdfAssets).mockRejectedValue(failure);

		await expect(printInventoryList(ROWS)).resolves.toBeUndefined();

		expect(error).toHaveBeenCalledWith(
			"[inventory] could not print the list",
			failure
		);
		expect(downloadPdf).not.toHaveBeenCalled();
	});
});
