import { ICONS as UI_ICONS } from "@j-os/design-system/icons";

/** Icon ligatures for every meaning the app names: the design system's generic
 *  ones plus J floor's domain ones. A key may have a single user, so the whole
 *  app reads its icons from one place. Keys name the meaning, not the picture;
 *  never override a design-system key. */
export const ICONS = {
	...UI_ICONS,
	unlock: "lock_open_right",
	lock: "lock",
	door: "door_front",
	doorStreet: "apartment",
	task: "task_alt",
	stepDone: "check_circle",
	project: "target",
	venture: "rocket_launch",
	status: "flag",
	start: "start",
	end: "horizontal_align_right",
	date: "event",
	description: "notes",
	agreement: "description",
	itemType: "important_devices",
	category: "category",
	productStage: "trending_up",
	fundingStage: "payments",
	whyJoin: "forum",
	pastBuilt: "history",
	assetTag: "sell",
	decline: "close",
	registered: "celebration",
	vertical: "category",
	assignees: "group",
	teamSize: "group",
	members: "group",
	community: "group",
	person: "person",
	memberApplication: "how_to_reg",
	guestApplication: "identity_platform",
	upgradeToMember: "person_add",
	host: "handshake",
	name: "text_fields_alt",
	role: "badge",
	kickOut: "block",
	signOut: "logout",
	departed: "person_remove",
	email: "mail",
	phone: "call",
	link: "link",
	share: "share",
	wifi: "wifi",
	notifications: "notifications",
	print: "print",
	qr: "qr_code_2",
	inventory: "inventory_2",
	events: "event",
	space: "factory",
} as const;
