// apps/web/emails/build.ts
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { render } from "jsx-email";
import { compile } from "jsx-email/compile";

const ROOT = resolve(import.meta.dirname);
const OUT_DIR = resolve(ROOT, "../convex/emails/generated");

// Registry: one entry per template. `fields` are the dynamic prop names; each
// becomes a sentinel `__JF_<UPPER>__`. `logoUrl` is shared by every template.
type ListField = {
	item: string[];
	html: string;
	text: string;
};

type Entry = {
	name: string;
	file: string;
	fields: string[];
	/**
	 * Fields that are a list of records. The generated function takes
	 * `{ <item keys>: string }[]` and renders each record through `html`
	 * and `text`, replacing `{key}` placeholders. Every item value is
	 * HTML-escaped for the HTML part (the plain-text part stays raw), so
	 * callers never pre-escape.
	 */
	listFields?: Partial<Record<string, ListField>>;
};

const TEMPLATES: Entry[] = [
	{
		name: "applicationReceived",
		file: "templates/applicationReceived.tsx",
		fields: ["name", "logoUrl", "privacyUrl"],
	},
	{
		name: "alreadyActive",
		file: "templates/alreadyActive.tsx",
		fields: ["greeting", "signinUrl", "logoUrl", "privacyUrl"],
	},
	{
		name: "reapplyAfter",
		file: "templates/reapplyAfter.tsx",
		fields: ["until", "logoUrl", "privacyUrl"],
	},
	{
		name: "alreadyUnderReview",
		file: "templates/alreadyUnderReview.tsx",
		fields: ["logoUrl", "privacyUrl"],
	},
	{
		name: "approvalMember",
		file: "templates/approvalMember.tsx",
		fields: ["name", "signinUrl", "logoUrl"],
	},
	{
		name: "memberUpgrade",
		file: "templates/memberUpgrade.tsx",
		fields: ["name", "signinUrl", "logoUrl"],
	},
	{
		name: "approvalGuest",
		file: "templates/approvalGuest.tsx",
		fields: ["name", "fromDate", "untilDate", "signinUrl", "logoUrl"],
	},
	{
		name: "approvalGuestOpen",
		file: "templates/approvalGuestOpen.tsx",
		fields: ["name", "signinUrl", "logoUrl"],
	},
	{
		name: "rejection",
		file: "templates/rejection.tsx",
		fields: ["name", "venture", "logoUrl"],
	},
	{
		name: "magicLink",
		file: "templates/magicLink.tsx",
		fields: ["url", "logoUrl"],
	},
	{
		name: "signedAgreement",
		file: "templates/signedAgreement.tsx",
		fields: ["name", "logoUrl"],
	},
	{
		name: "verifyApplication",
		file: "templates/verifyApplication.tsx",
		fields: ["confirmUrl", "logoUrl", "privacyUrl"],
	},
	{
		name: "verifyVisitor",
		file: "templates/verifyVisitor.tsx",
		fields: ["confirmUrl", "logoUrl", "privacyUrl"],
	},
	{
		name: "confirmEmailChange",
		file: "templates/confirmEmailChange.tsx",
		fields: ["confirmUrl", "logoUrl"],
	},
	{
		name: "emailChanged",
		file: "templates/emailChanged.tsx",
		fields: ["newEmail", "logoUrl"],
	},
	{
		name: "eventInvite",
		file: "templates/eventInvite.tsx",
		fields: ["eventName", "confirmUrl", "logoUrl", "privacyUrl"],
	},
	{
		name: "boardNewApplication",
		file: "templates/boardNewApplication.tsx",
		fields: [
			"applicantName",
			"venture",
			"reviewUrl",
			"manageUrl",
			"logoUrl",
		],
	},
	{
		name: "taskAssigned",
		file: "templates/taskAssigned.tsx",
		fields: ["name", "taskTitle", "viewUrl", "manageUrl", "logoUrl"],
	},
	{
		name: "projectAssigned",
		file: "templates/projectAssigned.tsx",
		fields: ["name", "projectName", "viewUrl", "manageUrl", "logoUrl"],
	},
	{
		name: "boardDoorAlert",
		file: "templates/boardDoorAlert.tsx",
		fields: [
			"headline",
			"detail",
			"consequence",
			"diagnosticsUrl",
			"manageUrl",
			"logoUrl",
		],
	},
	{
		name: "boardLifecycleAlert",
		file: "templates/boardLifecycleAlert.tsx",
		fields: ["headline", "rows", "communityUrl", "manageUrl", "logoUrl"],
		listFields: {
			rows: {
				item: ["name", "url", "code", "detail"],
				html: '<p style="margin:0 0 12px"><a href="{url}">{name}</a>: {code} ({detail})</p>',
				text: "{name}: {code} ({detail}) {url}\n",
			},
		},
	},
	{
		name: "notice",
		file: "templates/notice.tsx",
		fields: [
			"heading",
			"body",
			"ctaLabel",
			"ctaUrl",
			"manageUrl",
			"logoUrl",
		],
	},
];

function sentinel(field: string): string {
	// eslint-disable-next-line no-restricted-syntax -- builds a sentinel token, not UI text
	return `__JF_${field.replace(/[A-Z]/g, (c) => `_${c}`).toUpperCase()}__`;
}

function header(): string {
	return "// AUTO-GENERATED by emails/build.ts — do not edit by hand.\n// Run `bun run --filter @j-os/web email:build` to regenerate.\n";
}

function constName(field: string, part: "HTML" | "TEXT"): string {
	// eslint-disable-next-line no-restricted-syntax -- builds an identifier, not UI text
	return `${field.toUpperCase()}_${part}`;
}

function moduleSource(entry: Entry, html: string, text: string): string {
	const lists = entry.listFields ?? {};
	const propsType = entry.fields
		.map((f) => {
			const list = lists[f];
			return list
				? `\t${f}: { ${list.item.map((k) => `${k}: string`).join("; ")} }[];`
				: `\t${f}: string;`;
		})
		.join("\n");
	const destructured = `{ ${entry.fields.join(", ")} }`;
	const listConsts = entry.fields
		.flatMap((f) => {
			const list = lists[f];
			return list
				? [
						`const ${constName(f, "HTML")} = ${JSON.stringify(list.html)};\nconst ${constName(f, "TEXT")} = ${JSON.stringify(list.text)};\n`,
					]
				: [];
		})
		.join("\n");
	// One-pass replace so a value containing `{key}` is never re-substituted.
	function listExpr(f: string, list: ListField, escape: boolean): string {
		const keys = list.item.join("|");
		const value = escape ? "escapeHtml(item[k])" : "item[k]";
		const tpl = constName(f, escape ? "HTML" : "TEXT");
		return `${f}.map((item) => ${tpl}.replace(/\\{(${keys})\\}/g, (_, k: keyof (typeof ${f})[number]) => ${value})).join("")`;
	}
	// HTML substitution escapes values; the plain-text substitution uses raw
	// values (entity-encoding would corrupt the text part).
	const htmlSubs = entry.fields
		.map((f) => {
			const list = lists[f];
			return `\t\t.split(${JSON.stringify(sentinel(f))}).join(${list ? listExpr(f, list, true) : `escapeHtml(${f})`})`;
		})
		.join("\n");
	const textSubs = entry.fields
		.map((f) => {
			const list = lists[f];
			return `\t\t.split(${JSON.stringify(sentinel(f))}).join(${list ? listExpr(f, list, false) : f})`;
		})
		.join("\n");
	return `${header()}import { escapeHtml } from "../escape.ts";

const HTML = ${JSON.stringify(html)};
const TEXT = ${JSON.stringify(text)};
${listConsts}
export type ${cap(entry.name)}Props = {
${propsType}
};

export function ${entry.name}(${destructured}: ${cap(entry.name)}Props): { html: string; text: string } {
	return {
		html: HTML
${htmlSubs},
		text: TEXT
${textSubs},
	};
}
`;
}

function cap(s: string): string {
	// eslint-disable-next-line no-restricted-syntax -- builds an identifier, not UI text
	return s.charAt(0).toUpperCase() + s.slice(1);
}

async function main(): Promise<void> {
	const check = process.argv.includes("--check");
	const tmp = await mkdtemp(join(tmpdir(), "jfemail-"));
	let failed = false;
	try {
		for (const entry of TEMPLATES) {
			const results = await compile({
				files: [resolve(ROOT, entry.file)],
				hashFiles: false,
				outDir: tmp,
			});
			const [compiled] = results;
			const mod = (await import(pathToFileURL(compiled.path).href)) as {
				Template: (props: Record<string, string>) => unknown;
			};
			const sentinels = Object.fromEntries(
				entry.fields.map((f) => [f, sentinel(f)])
			);
			const html = await render(mod.Template(sentinels) as never, {
				inlineCss: true,
			});
			const text = await render(mod.Template(sentinels) as never, {
				plainText: true,
			});
			// Assert every declared sentinel survived rendering somewhere.
			for (const f of entry.fields) {
				const s = sentinel(f);
				if (!html.includes(s) && !text.includes(s)) {
					throw new Error(
						`[email:build] ${entry.name}: sentinel ${s} missing from rendered output`
					);
				}
			}
			const source = moduleSource(entry, html, text);
			const target = resolve(OUT_DIR, `${entry.name}.ts`);
			if (check) {
				const current = await readFile(target, "utf8").catch(() => "");
				if (current !== source) {
					failed = true;

					console.error(
						`[email:check] ${entry.name}.ts is stale — run email:build`
					);
				}
			} else {
				await writeFile(target, source, "utf8");

				console.log(`[email:build] wrote ${entry.name}.ts`);
			}
		}
	} finally {
		await rm(tmp, { recursive: true, force: true });
	}
	if (failed) process.exit(1);
}

await main();
